 # Specify docker-compose version
version: '3'
 
# Define the services/containers to be run
services:
 client: # Name of the first service
   container_name: apphub_web
   build: 
     context: ./Web
     dockerfile: DOCKERFILE
   ports:
     - "80"
   depends_on:
     - server
     - database
   links:
     - server
 server: # Name of the second service
   container_name: apphub_server
   build: 
     context: ./BackEnd
     dockerfile: DOCKERFILE
   ports:
     - "3000"
   links:
     - database
 database: # Name of the third service
   container_name: apphub_database
   image: mongo
   restart: always
   ports:
     - "27017"