 # Specify docker-compose version
version: '3'
 
# Define the services/containers to be run
services:
 client: # Name of the first service
   container_name: apphub_web
   restart: on-failure
   build: 
     context: ./Web
     dockerfile: DOCKERFILE
   ports:
     - "80:80"
   depends_on:
     - server
     - database
   links:
     - server
 server: # Name of the second service
   container_name: apphub_server
   restart: on-failure
   build: 
     context: ./BackEnd
     dockerfile: DOCKERFILE
   ports:
     - "3000:3000"
   links:
     - database
 database: # Name of the third service
   container_name: apphub_database
   restart: on-failure
   image: mongo
   ports:
     - "27017:27017"