let SERVER_PORT = "3000";

let DOMAIN_NAME = "localhost:" + SERVER_PORT;

let JWT_SECRET = "THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET, IT CAN BE ANY STRING";

let MONGODB_IP = "database";
let MONGODB_PORT = "27017";
let MONGODB_DATABASE_NAME = "apphub";

let GITLAB_IP = "http://localhost/api/v4/";
let GITLAB_IP_SUFFIX = "api/v4/";
let GITLAB_PRIVATE_TOKEN = "PRIVATE_GITLAB_TOKEN";

let ANDROID_GROUP = "groups/8/";
let IOS_GROUP = "groups/9/";

let VERSION_REGEX = "^v[0-9]+.[0-9]+.[0-9]+$";
let NO_VERSION_TEXT = "No version";

let LOGIN_TOKEN_VALIDITY = "24h";

module.exports = {
    DOMAIN_NAME,
    SERVER_PORT,
    JWT_SECRET,
    MONGODB_IP,
    MONGODB_PORT,
    MONGODB_DATABASE_NAME,
    GITLAB_IP,
    GITLAB_IP_SUFFIX,
    GITLAB_PRIVATE_TOKEN,
    ANDROID_GROUP,
    IOS_GROUP,
    VERSION_REGEX,
    NO_VERSION_TEXT,
    LOGIN_TOKEN_VALIDITY
};
